#Max number of times you can use /back
#Range: > 0
maxBack = 0
#Max homes
#Range: > 0
maxHomes = 1
#/back cooldown in seconds
#Range: 0 ~ 604800
backCooldown = 604800
#/spawn cooldown in seconds
#Range: 0 ~ 604800
spawnCooldown = 0
#/warp cooldown in seconds
#Range: 0 ~ 604800
warpCooldown = 0
#/home cooldown in seconds
#Range: 0 ~ 604800
homeCooldown = 0
#/tpa cooldown in seconds
#Range: 0 ~ 604800
tpaCooldown = 0
#/rtp cooldown in seconds
#Range: 0 ~ 604800
rtpCooldown = 300
#Number of tries before /rtp gives up
#Range: 1 ~ 1000
rtpMaxTries = 10
#/rtp min distance from spawn point
#Range: 0.0 ~ 3.0E7
rtpMinDistance = 500
#/rtp max distance from spawn point
#Range: 0.0 ~ 3.0E7
rtpMaxDistance = 10000.0

